### ISSUE TITLE
邮箱535错误

### ISSUE THREAD

**Issue by LeeMystique** [xuess/puppeteer-sign#2]
您好，感谢您开发此工具。

我部署后在设置邮箱方面出现了一些错误，无论是网易邮箱还是QQ邮箱都打开了smtp服务，并获取授权码，在config中配置好邮箱密码（授权码）后，log中都会出现535错误，应该是授权出了一些什么问题。我用同样的账号密码在iPhone邮箱设置中是可以正常访问的。

以下是报错信息：

0|main  | Error: Invalid login: 535 Error: authentication failed
0|main  |     at SMTPConnection._formatError (/root/puppeteer-sign/node_modules/_nodemailer@4.7.0@nodemailer/lib/smtp-connection/index.js:605:19)
0|main  |     at SMTPConnection._actionAUTHComplete (/root/puppeteer-sign/node_modules/_nodemailer@4.7.0@nodemailer/lib/smtp-connection/index.js:1340:34)
0|main  |     at SMTPConnection.<anonymous> (/root/puppeteer-sign/node_modules/_nodemailer@4.7.0@nodemailer/lib/smtp-connection/index.js:378:26)
0|main  |     at SMTPConnection._processResponse (/root/puppeteer-sign/node_modules/_nodemailer@4.7.0@nodemailer/lib/smtp-connection/index.js:764:20)
0|main  |     at SMTPConnection._onData (/root/puppeteer-sign/node_modules/_nodemailer@4.7.0@nodemailer/lib/smtp-connection/index.js:570:14)
0|main  |     at TLSSocket.<anonymous> (/root/puppeteer-sign/node_modules/_nodemailer@4.7.0@nodemailer/lib/smtp-connection/index.js:522:47)
0|main  |     at TLSSocket.emit (events.js:314:20)
0|main  |     at addChunk (_stream_readable.js:297:12)
0|main  |     at readableAddChunk (_stream_readable.js:272:9)
0|main  |     at TLSSocket.Readable.push (_stream_readable.js:213:10) {
0|main  |   code: 'EAUTH',
0|main  |   response: '535 Error: authentication failed',
0|main  |   responseCode: 535,
0|main  |   command: 'AUTH PLAIN'
0|main  | }

期待您的回复，祝好。

**Comment by LeeMystique** [comment]
已解决，需修改/lib/mail.js的邮箱配置。
请关闭此问题。
